include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
  - '**/*.g.dart'

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    use_key_in_widget_constructors: false
    prefer_single_quotes: true
    use_build_context_synchronously: false
